### ISSUE TITLE
Updating Docker image to use rust:alpine ?

### ISSUE THREAD

**Issue by grouchal** [simonhdickson/tvheadproxy#1]
Hi there, is there any reason why the docker image doesn't use alpine?

I would appreciate if the tvheadproxy could be as small as possible as I run it on a sinology which is a little resource constrained.

Hope you can help - perhaps you could publish two versions?

Thanks in advance.

**Comment by simonhdickson** [comment]
Hi

Only the build image uses rust, the final build is actually alpine based (see https://hub.docker.com/r/simonhdickson/tvheadproxy for a pre-built image).

I should have added a link to the docker hub in the readme so people are aware this exists.

**Comment by grouchal** [comment]
Great to know - yes please update the docks.
